# Specify prior
prior:
  module: 'ili.utils'
  class: 'Uniform'
  args:
    low: [-10]
    high: [10]

embedding_net:
  module: 'ili.embedding'
  class: 'FCN'
  args:
    n_hidden: [128,64,32]
    act_fn: "SiLU"

# Specify the inference model
model:
  backend: 'lampe'
  engine: 'NPE'  # Neural Posterior Estimation
  name: 'bias_NPE_intermediate_GEM'
  nets:
    - model: 'nsf'  # Masked Autoregressive Flow
      hidden_features: 64
      num_transforms: 4

# Specify the neural training hyperparameters   
train_args:
  training_batch_size: 1024
  learning_rate: 0.0005
  stop_after_epochs: 50

device: 'cuda'  # Run on GPU
out_dir: '/mnt/home/fmaion/storage/projects/bias_priors/training_results/bias_NPE_intermediate_GEM'  # Where to save the posterior
